services:
  - type: web
    name: mkraut-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
